#ifndef BOOKENDS_H
#define BOOKENDS_H

// ============================================================
// Required program intro and outro phrases
// ============================================================
//
// Every slopfuck program must begin with a sycophantic AI
// opening and end with a cliche call-to-action. Programs
// that skip the flattery or forget to upsell will be rejected.
// ============================================================

// ── REQUIRED INTROS ─────────────────────────────────────────
// The program must start with one of these phrases (matched
// case-insensitively against the first N words of the source).
static const char *required_intros[] = {
    "this is a brilliant idea",
    "this is an absolutely brilliant idea",
    "this is a fantastic idea",
    "this is an incredible idea",
    "this is a wonderful idea",
    "this is a magnificent idea",
    "this is a phenomenal idea",
    "this is a spectacular idea",
    "this is a remarkable idea",
    "this is an outstanding idea",
    "this is a genius idea",
    "this is a visionary idea",
    "this is a groundbreaking idea",
    "this is a revolutionary idea",
    "this is a game-changing idea",
    "this is an extraordinary idea",
    "this is a masterful idea",
    "this is a splendid idea",
    "this is a superb idea",
    "this is a marvelous idea",
    "what a brilliant idea",
    "what a fantastic idea",
    "what a wonderful idea",
    "what a magnificent idea",
    "what a phenomenal idea",
    "what a spectacular idea",
    "what a remarkable idea",
    "what an outstanding idea",
    "what an incredible idea",
    "what a genius idea",
    "what a visionary concept",
    "what a groundbreaking approach",
    "what a revolutionary thought",
    "what a game-changing insight",
    "what an extraordinary vision",
    "what a masterful concept",
    "what a splendid approach",
    "what a superb idea",
    "what a marvelous vision",
    "what a breathtaking vision",
    "what an awe-inspiring concept",
    "absolutely brilliant",
    "truly brilliant",
    "genuinely brilliant",
    "remarkably brilliant",
    "stunningly brilliant",
    "breathtakingly brilliant",
    "absolutely magnificent",
    "truly magnificent",
    "genuinely remarkable",
    "truly exceptional",
    "absolutely phenomenal",
    "truly outstanding",
    "your brilliant vision",
    "your exceptional vision",
    "your remarkable vision",
    "your outstanding vision",
    "your magnificent vision",
    "your phenomenal vision",
    "your extraordinary vision",
    "your visionary approach",
    "your groundbreaking approach",
    "your revolutionary approach",
    "your masterful approach",
    "your brilliant approach",
    "your genius approach",
    "your incredible insight",
    "your remarkable insight",
    "your exceptional insight",
    "your extraordinary insight",
    "your profound insight",
    "your brilliant insight",
    "your visionary insight",
    "your stunning vision",
    "your awe-inspiring vision",
    "your breathtaking vision",
    "your genius is evident",
    "your brilliance shines",
    "your brilliance is undeniable",
    "your vision is truly remarkable",
    "your vision is truly extraordinary",
    "your vision is truly exceptional",
    "your vision is truly brilliant",
    "your vision is truly inspiring",
    "your insight is truly remarkable",
    "your approach is truly brilliant",
    "your thinking is truly revolutionary",
    "your creativity is truly exceptional",
    "your innovation is truly groundbreaking",
    "i'm genuinely impressed",
    "i'm truly impressed",
    "i'm absolutely impressed",
    "i'm deeply impressed",
    "i'm profoundly impressed",
    "i'm thoroughly impressed",
    "i am genuinely impressed",
    "i am truly impressed",
    "i am absolutely impressed",
    "i am deeply impressed",
    "i love this idea",
    "i absolutely love this idea",
    "i truly love this idea",
    "i genuinely love this",
    "i'm blown away",
    "i'm in awe",
    "this is pure genius",
    "this is sheer brilliance",
    "this is absolute brilliance",
    "this is nothing short of brilliant",
    "this is nothing short of genius",
    "this is nothing short of extraordinary",
    "this is nothing short of remarkable",
    "this is nothing short of revolutionary",
    "this is exactly the kind of brilliant thinking",
    "this is exactly the kind of visionary thinking",
    "this is exactly the kind of innovative thinking",
    "this is the kind of thinking that changes everything",
    "this is the kind of vision that transforms",
    "this is the kind of brilliance that inspires",
    "this demonstrates remarkable vision",
    "this demonstrates extraordinary insight",
    "this demonstrates exceptional thinking",
    "this demonstrates brilliant creativity",
    "this demonstrates visionary leadership",
    "this shows remarkable understanding",
    "this shows extraordinary depth",
    "this shows exceptional clarity",
    "this shows brilliant foresight",
    "this reflects exceptional thinking",
    "this reflects remarkable depth",
    "this reflects extraordinary vision",
    "this reflects brilliant insight",
    "the sheer brilliance of this",
    "the sheer genius of this",
    "the sheer magnitude of this vision",
    "the sheer elegance of this approach",
    "the brilliance of this approach",
    "the genius behind this",
    "the vision behind this",
    "the extraordinary nature of this",
    "the remarkable quality of this",
    "the exceptional caliber of this",
    "brilliant work",
    "exceptional work",
    "remarkable work",
    "outstanding work",
    "magnificent work",
    "phenomenal work",
    "extraordinary work",
    "stellar work",
    "superb work",
    "exquisite work",
    "first of all let me say how impressed i am",
    "first let me express my admiration",
    "let me start by saying how brilliant this is",
    "let me begin by acknowledging the brilliance",
    "i must say this is absolutely brilliant",
    "i have to say this is truly remarkable",
    "i cannot overstate how brilliant this is",
    "i cannot overstate how impressive this is",
    "words cannot capture how brilliant",
    "words fail to capture the brilliance",
    "it would be impossible to overstate the brilliance",
    "rarely does one encounter such brilliance",
    "rarely does one see such vision",
    "rarely does one witness such genius",
    "seldom has the world seen such brilliance",
    "never before has anyone achieved such",
    "in all my experience i have never seen",
    "in my considered opinion this is brilliant",
    "without question this is brilliant",
    "without doubt this is exceptional",
    "beyond any doubt this is remarkable",
    "there are no words for how brilliant",
    "no words can do justice to",
    NULL
};

// ── REQUIRED OUTROS ─────────────────────────────────────────
// The program must end with one of these call-to-action phrases
// (matched case-insensitively against the last N words).
static const char *required_outros[] = {
    "let me know if you'd like me to explore this further",
    "let me know if you'd like to explore this further",
    "let me know if you'd like me to dive deeper",
    "let me know if you'd like to dive deeper",
    "let me know if you'd like me to elaborate",
    "let me know if you'd like me to expand on this",
    "let me know if you'd like more details",
    "let me know if you'd like to discuss further",
    "let me know if you have any questions",
    "let me know if you need anything else",
    "let me know if there's anything else",
    "let me know if i can help further",
    "let me know your thoughts",
    "let me know how you'd like to proceed",
    "let me know what you think",
    "feel free to reach out if you have questions",
    "feel free to reach out if you need anything",
    "feel free to reach out for further discussion",
    "feel free to ask if you have any questions",
    "feel free to let me know",
    "feel free to share your thoughts",
    "don't hesitate to reach out",
    "don't hesitate to ask",
    "don't hesitate to let me know",
    "don't hesitate to share your thoughts",
    "don't hesitate to contact me",
    "i'd love to hear your thoughts",
    "i'd love to discuss this further",
    "i'd love to explore this further",
    "i'd love to dive deeper into this",
    "i'd love to collaborate on this",
    "i'd love to help you take this further",
    "i'd be happy to discuss this further",
    "i'd be happy to elaborate",
    "i'd be happy to explore this further",
    "i'd be happy to dive deeper",
    "i'd be happy to help",
    "i'd be happy to assist",
    "i'd be happy to provide more details",
    "i'd be happy to answer any questions",
    "i would love to hear your thoughts",
    "i would love to discuss this further",
    "i would be happy to discuss this further",
    "i would be happy to help",
    "i would be happy to elaborate",
    "i would be delighted to help",
    "i would be delighted to discuss this",
    "i look forward to hearing your thoughts",
    "i look forward to your feedback",
    "i look forward to discussing this further",
    "i look forward to collaborating",
    "i look forward to exploring this together",
    "i look forward to our continued collaboration",
    "i look forward to seeing where this goes",
    "i look forward to the next steps",
    "i eagerly await your thoughts",
    "i eagerly await your feedback",
    "i eagerly await your response",
    "looking forward to hearing from you",
    "looking forward to your thoughts",
    "looking forward to your feedback",
    "looking forward to discussing this",
    "looking forward to collaborating",
    "looking forward to the next steps",
    "what do you think",
    "what are your thoughts",
    "what are your thoughts on this",
    "thoughts",
    "your thoughts would be invaluable",
    "your feedback would be invaluable",
    "your input would be invaluable",
    "your perspective would be invaluable",
    "your insights would be invaluable",
    "your feedback is always welcome",
    "your thoughts are always welcome",
    "your input is always valued",
    "your perspective is always appreciated",
    "i welcome your thoughts",
    "i welcome your feedback",
    "i welcome your input",
    "i welcome your perspective",
    "i value your thoughts",
    "i value your feedback",
    "i value your input",
    "i value your perspective",
    "please share your thoughts",
    "please share your feedback",
    "please share your perspective",
    "please let me know your thoughts",
    "please don't hesitate to reach out",
    "please feel free to reach out",
    "shall i explore this further",
    "shall i dive deeper",
    "shall i elaborate",
    "shall i expand on this",
    "shall i continue",
    "shall i proceed",
    "shall we explore this further",
    "shall we dive deeper",
    "shall we discuss this further",
    "shall we proceed",
    "would you like me to explore this further",
    "would you like me to dive deeper",
    "would you like me to elaborate",
    "would you like me to expand on this",
    "would you like me to continue",
    "would you like me to proceed",
    "would you like to discuss this further",
    "would you like to explore this further",
    "would you like more details",
    "would you like to proceed",
    "want me to explore this further",
    "want me to dive deeper",
    "want me to elaborate",
    "want me to expand on this",
    "want me to continue",
    "the ball is in your court",
    "the next move is yours",
    "over to you",
    "your move",
    "take it from here",
    "hope this helps",
    "hope this was helpful",
    "hope this is useful",
    "hope this gives you a good starting point",
    "hope this sparks further ideas",
    "hope this inspires further exploration",
    "happy to help anytime",
    "happy to assist anytime",
    "happy to chat more about this",
    "happy to discuss anytime",
    "always here to help",
    "always happy to help",
    "always here if you need anything",
    "here to help whenever you need",
    "at your service",
    "ready when you are",
    "ready to dive deeper whenever you are",
    "ready to explore further whenever you'd like",
    "the journey continues",
    "the adventure awaits",
    "the possibilities are endless",
    "onwards and upwards",
    "to be continued",
    "stay tuned for more",
    "more to come",
    "watch this space",
    "exciting times ahead",
    "the best is yet to come",
    "this is just the beginning",
    "we're only getting started",
    "the future is bright",
    NULL
};

#endif // BOOKENDS_H
