#ifndef KEYWORDS_H
#define KEYWORDS_H

// ============================================================
// slopfuck keyword tables
// ============================================================
//
// Each brainfuck operation maps to a pool of interchangeable
// AI-slop keywords. The interpreter treats every keyword in a
// pool identically. Anything not in any pool is filler/comment.
//
// Pointer movement uses em dash (—) and en dash (–) only.
// They are detected as UTF-8 byte sequences in the lexer.
//
// The six word-based pools are below.
// ============================================================

// ── INCREMENT (+) ───────────────────────────────────────────
// Aspirational AI verbs: things that sound transformative
// but say nothing.
static const char *kw_inc[] = {
    "delve",
    "foster",
    "nurture",
    "cultivate",
    "elevate",
    "leverage",
    "spearhead",
    "streamline",
    "optimize",
    "enhance",
    "amplify",
    "accelerate",
    "empower",
    "unlock",
    "unleash",
    "transform",
    "revolutionize",
    "innovate",
    "pioneer",
    "champion",
    "harness",
    "maximize",
    "bolster",
    "strengthen",
    "fortify",
    "enrich",
    "galvanize",
    "propel",
    "catalyze",
    "ignite",
    "inspire",
    "invigorate",
    "rejuvenate",
    "revitalize",
    "energize",
    "supercharge",
    "turbocharge",
    "synergize",
    "harmonize",
    "orchestrate",
    "curate",
    "craft",
    "architect",
    "forge",
    "sculpt",
    "refine",
    "polish",
    "hone",
    "sharpen",
    "calibrate",
    "tailor",
    "personalize",
    "reimagine",
    "redefine",
    "reinvent",
    "rethink",
    "reshape",
    "overhaul",
    "modernize",
    "digitize",
    "automate",
    "integrate",
    "consolidate",
    "unify",
    "align",
    "converge",
    "bridge",
    "interweave",
    "intertwine",
    "fuse",
    "merge",
    "blend",
    "synthesize",
    "distill",
    "crystallize",
    "coalesce",
    "aggregate",
    "assemble",
    "construct",
    "establish",
    "institute",
    "inaugurate",
    "initiate",
    "deploy",
    "implement",
    "execute",
    "actualize",
    "materialize",
    "realize",
    "manifest",
    "embody",
    "exemplify",
    "showcase",
    "underscore",
    "accentuate",
    "illuminate",
    "elucidate",
    "articulate",
    "convey",
    "advocate",
    "promote",
    "advance",
    "further",
    "evolve",
    "expand",
    "scale",
    "broaden",
    "widen",
    "deepen",
    "heighten",
    "intensify",
    "magnify",
    "augment",
    "supplement",
    "complement",
    "reinforce",
    "buttress",
    "undergird",
    "underpin",
    "sustain",
    "safeguard",
    "facilitate",
    "enable",
    "equip",
    "furnish",
    "generate",
    "produce",
    "originate",
    "conceive",
    "ideate",
    "envision",
    "visualize",
    "conceptualize",
    "formulate",
    "devise",
    "discover",
    "uncover",
    "reveal",
    "unveil",
    "spotlight",
    "prioritize",
    "expedite",
    "hasten",
    "operationalize",
    "incentivize",
    "democratize",
    "decentralize",
    "futureproof",
    "bulletproof",
    "weatherproof",
    "troubleshoot",
    "crowdsource",
    "brainstorm",
    "whiteboard",
    "ideation",
    "iterate",
    "pivot",
    "disrupt",
    "trailblaze",
    "benchmark",
    "greenlight",
    "fast-track",
    "upskill",
    "reskill",
    "onboard",
    "bootstrap",
    "incubate",
    "cross-pollinate",
    "dovetail",
    "springboard",
    "leapfrog",
    "catapult",
    "skyrocket",
    "moonshot",
    "quarterback",
    "spearheading",
    "stakeholder",
    "touchpoint",
    "bandwidth",
    "mindshare",
    "skillset",
    "toolset",
    "toolkit",
    "playbook",
    "roadmap",
    "blueprint",
    "gameplan",
    "masterplan",
    "deep-dive",
    "drill-down",
    "double-click",
    "unpack",
    "deconstruct",
    "reverse-engineer",
    "problem-solve",
    "solutionize",
    "productize",
    "monetize",
    "capitalize",
    "galvanizing",
    "revamp",
    "retool",
    "recalibrate",
    "re-envision",
    "re-architect",
    "future-proof",
    "value-add",
    "level-up",
    "power-up",
    "turbocharging",
    "supercharging",
    "hyperscale",
    "metastasize",
    NULL
};

// ── DECREMENT (−) ───────────────────────────────────────────
// Transition words, hedging, qualifiers: the connective tissue
// of AI slop that adds word count without adding meaning.
static const char *kw_dec[] = {
    "however",
    "moreover",
    "furthermore",
    "nonetheless",
    "additionally",
    "consequently",
    "subsequently",
    "accordingly",
    "therefore",
    "thus",
    "hence",
    "whereby",
    "meanwhile",
    "conversely",
    "alternatively",
    "notably",
    "significantly",
    "importantly",
    "crucially",
    "fundamentally",
    "essentially",
    "ultimately",
    "arguably",
    "undeniably",
    "undoubtedly",
    "unquestionably",
    "admittedly",
    "granted",
    "certainly",
    "surely",
    "indeed",
    "naturally",
    "obviously",
    "clearly",
    "evidently",
    "apparently",
    "presumably",
    "ostensibly",
    "seemingly",
    "effectively",
    "practically",
    "virtually",
    "largely",
    "broadly",
    "generally",
    "typically",
    "traditionally",
    "historically",
    "increasingly",
    "progressively",
    "gradually",
    "steadily",
    "consistently",
    "persistently",
    "continually",
    "perpetually",
    "invariably",
    "inevitably",
    "unavoidably",
    "irrefutably",
    "indisputably",
    "incontrovertibly",
    "categorically",
    "unequivocally",
    "emphatically",
    "resoundingly",
    "overwhelmingly",
    "predominantly",
    "primarily",
    "principally",
    "chiefly",
    "mainly",
    "mostly",
    "substantially",
    "considerably",
    "remarkably",
    "extraordinarily",
    "exceptionally",
    "particularly",
    "especially",
    "specifically",
    "precisely",
    "explicitly",
    "distinctly",
    "markedly",
    "strikingly",
    "noticeably",
    "tangibly",
    "measurably",
    "demonstrably",
    "observably",
    "discernibly",
    "palpably",
    "acutely",
    "profoundly",
    "deeply",
    "intensely",
    "immensely",
    "enormously",
    "tremendously",
    "vastly",
    "hugely",
    "massively",
    "extensively",
    "comprehensively",
    "exhaustively",
    "thoroughly",
    "meticulously",
    "rigorously",
    "diligently",
    "assiduously",
    "scrupulously",
    "conscientiously",
    "painstakingly",
    "carefully",
    "cautiously",
    "prudently",
    "judiciously",
    "wisely",
    "astutely",
    "shrewdly",
    "perceptively",
    "insightfully",
    "intuitively",
    "instinctively",
    "innately",
    "inherently",
    "intrinsically",
    "organically",
    "holistically",
    "symbiotically",
    "synergistically",
    "collaboratively",
    "collectively",
    "cooperatively",
    "reciprocally",
    "mutually",
    "simultaneously",
    "concurrently",
    "correspondingly",
    "analogously",
    "similarly",
    "likewise",
    "comparably",
    "proportionally",
    "commensurately",
    "appropriately",
    "suitably",
    "fittingly",
    "aptly",
    "pertinently",
    "relevantly",
    "pivotally",
    "instrumentally",
    "integrally",
    "indispensably",
    "critically",
    "vitally",
    "imperatively",
    "paramountly",
    "supremely",
    "preeminently",
    "quintessentially",
    "archetypally",
    "prototypically",
    "paradigmatically",
    "characteristically",
    "distinctively",
    "uniquely",
    "singularly",
    "uncommonly",
    "unprecedentedly",
    "unparalleled",
    "incomparably",
    "inimitably",
    "matchlessly",
    "peerlessly",
    "superlatively",
    "transcendently",
    "sublimely",
    "magnificently",
    "splendidly",
    "gloriously",
    "spectacularly",
    "phenomenally",
    "prodigiously",
    "stupendously",
    "astoundingly",
    "astonishingly",
    "staggeringly",
    "breathtakingly",
    "awe-inspiringly",
    "mind-bogglingly",
    "groundbreakingly",
    "trailblazingly",
    "pathbreakingly",
    "game-changingly",
    "world-changingly",
    "era-definingly",
    "epoch-makingly",
    "watershed",
    "seminal",
    "landmark",
    "milestone",
    "cornerstone",
    "bedrock",
    "linchpin",
    "fulcrum",
    "nexus",
    "locus",
    "crux",
    "nub",
    "gist",
    "kernel",
    NULL
};

// ── OUTPUT (.) ──────────────────────────────────────────────
// Abstract AI nouns: things that sound important but resist
// definition.
static const char *kw_out[] = {
    "tapestry",
    "landscape",
    "paradigm",
    "ecosystem",
    "framework",
    "synergy",
    "trajectory",
    "narrative",
    "discourse",
    "continuum",
    "spectrum",
    "mosaic",
    "kaleidoscope",
    "constellation",
    "pantheon",
    "cornucopia",
    "juxtaposition",
    "dichotomy",
    "duality",
    "polarity",
    "interplay",
    "confluence",
    "convergence",
    "intersection",
    "crossroads",
    "nexus",
    "fulcrum",
    "crucible",
    "catalyst",
    "prism",
    "lens",
    "mirror",
    "beacon",
    "compass",
    "lodestar",
    "touchstone",
    "benchmark",
    "yardstick",
    "litmus",
    "barometer",
    "bellwether",
    "harbinger",
    "precursor",
    "forerunner",
    "vanguard",
    "zeitgeist",
    "ethos",
    "pathos",
    "mythos",
    "logos",
    "gestalt",
    "weltanschauung",
    "schadenfreude",
    "wanderlust",
    "angst",
    "ennui",
    "malaise",
    "renaissance",
    "metamorphosis",
    "epiphany",
    "revelation",
    "awakening",
    "reckoning",
    "inflection",
    "precipice",
    "threshold",
    "cusp",
    "brink",
    "verge",
    "frontier",
    "horizon",
    "vista",
    "panorama",
    "terrain",
    "topography",
    "cartography",
    "archipelago",
    "labyrinth",
    "odyssey",
    "saga",
    "chronicle",
    "manifesto",
    "treatise",
    "compendium",
    "anthology",
    "repository",
    "reservoir",
    "wellspring",
    "fountainhead",
    "bedrock",
    "cornerstone",
    "keystone",
    "linchpin",
    "scaffolding",
    "infrastructure",
    "architecture",
    "superstructure",
    "underpinning",
    "substrate",
    "lattice",
    "matrix",
    "fabric",
    "texture",
    "grain",
    "fiber",
    "thread",
    "strand",
    "filament",
    "conduit",
    "pipeline",
    "channel",
    "artery",
    "vein",
    "capillary",
    "membrane",
    "interface",
    "threshold",
    "gateway",
    "portal",
    "nexus",
    "hub",
    "node",
    "vertex",
    "apex",
    "zenith",
    "pinnacle",
    "summit",
    "acme",
    "crescendo",
    "climax",
    "denouement",
    "coda",
    "epilogue",
    "postscript",
    "addendum",
    "corollary",
    "ramification",
    "implication",
    "repercussion",
    "reverberation",
    "resonance",
    "dissonance",
    "cadence",
    "rhythm",
    "tempo",
    "momentum",
    "velocity",
    "trajectory",
    "vector",
    "gradient",
    "spectrum",
    "palette",
    "repertoire",
    "lexicon",
    "vernacular",
    "parlance",
    "nomenclature",
    "taxonomy",
    "ontology",
    "epistemology",
    "methodology",
    "pedagogy",
    "andragogy",
    "heuristic",
    "algorithm",
    "calculus",
    "algebra",
    "geometry",
    "topology",
    "morphology",
    "anatomy",
    "physiology",
    "pathology",
    "etiology",
    "prognosis",
    "diagnosis",
    "synthesis",
    "analysis",
    "thesis",
    "antithesis",
    "dialectic",
    "rhetoric",
    "polemic",
    "apologia",
    "exegesis",
    "hermeneutics",
    "semiotics",
    "phenomenology",
    "teleology",
    "eschatology",
    "cosmology",
    "microcosm",
    "macrocosm",
    "ecosystem",
    "biosphere",
    "technosphere",
    "noosphere",
    "stratosphere",
    "ionosphere",
    "atmosphere",
    "milieu",
    "ambiance",
    "aura",
    "essence",
    "quintessence",
    "embodiment",
    "manifestation",
    "instantiation",
    "iteration",
    "permutation",
    "configuration",
    "constellation",
    "orchestration",
    "choreography",
    "symphony",
    "opus",
    NULL
};

// ── INPUT (,) ───────────────────────────────────────────────
// Enthusiastic affirmations and filler exclamations: the
// hollow positivity of AI responses.
// These are matched case-insensitively, exclamation marks optional.
static const char *kw_in[] = {
    "absolutely",
    "certainly",
    "indeed",
    "definitely",
    "undoubtedly",
    "unquestionably",
    "indubitably",
    "affirmative",
    "positively",
    "assuredly",
    "decidedly",
    "emphatically",
    "resolutely",
    "wholeheartedly",
    "unreservedly",
    "unconditionally",
    "categorically",
    "incontestably",
    "irrefutably",
    "unmistakably",
    "self-evidently",
    "axiomatically",
    "tautologically",
    "manifestly",
    "patently",
    "transparently",
    "conspicuously",
    "blatantly",
    "flagrantly",
    "glaringly",
    "blindingly",
    "screamingly",
    "thunderously",
    "rapturously",
    "ecstatically",
    "euphorically",
    "exuberantly",
    "effervescently",
    "ebulliently",
    "vivaciously",
    "vibrantly",
    "dynamically",
    "energetically",
    "enthusiastically",
    "passionately",
    "fervently",
    "ardently",
    "zealously",
    "devoutly",
    "avidly",
    "keenly",
    "eagerly",
    "hungrily",
    "voraciously",
    "ravenously",
    "insatiably",
    "inexhaustibly",
    "tirelessly",
    "relentlessly",
    "unwaveringly",
    "unflinchingly",
    "unyieldingly",
    "unswervingly",
    "steadfastly",
    "resolutely",
    "tenaciously",
    "doggedly",
    "persistently",
    "indefatigably",
    "unflaggingly",
    "untiringly",
    "unceasingly",
    "unremittingly",
    "perpetually",
    "eternally",
    "infinitely",
    "boundlessly",
    "limitlessly",
    "immeasurably",
    "incalculably",
    "unfathomably",
    "incomprehensibly",
    "inconceivably",
    "unimaginably",
    "mind-blowingly",
    "jaw-droppingly",
    "eye-openingly",
    "breathtakingly",
    "heartstoppingly",
    "spine-tinglingly",
    "soul-stirringly",
    "awe-inspiringly",
    "wonder-struckly",
    "marvelously",
    "wondrously",
    "miraculously",
    "magically",
    "enchantingly",
    "mesmerizingly",
    "captivatingly",
    "fascinatingly",
    "enthrallingly",
    "spellbindingly",
    "rivettingly",
    "grippingly",
    "compellingly",
    "convincingly",
    "persuasively",
    "cogently",
    "eloquently",
    "articulately",
    "lucidly",
    "pellucidly",
    "limpidly",
    "crystallinely",
    "pristinely",
    "immaculately",
    "impeccably",
    "flawlessly",
    "faultlessly",
    "perfectly",
    "ideally",
    "optimally",
    "supremely",
    "consummately",
    "exquisitely",
    "sublimely",
    "divinely",
    "celestially",
    "transcendently",
    "ethereally",
    "otherworldly",
    "preternaturally",
    "supernaturally",
    "extraordinarily",
    "phenomenally",
    "prodigiously",
    "stupendously",
    "colossally",
    "monumentally",
    "titanically",
    "herculeanly",
    "olympianly",
    "prometheanly",
    "sisypheanly",
    "quixotically",
    "romantically",
    "poetically",
    "lyrically",
    "melodically",
    "harmoniously",
    "symphonically",
    "orchestrally",
    "virtuosically",
    "maestroly",
    "brilliantly",
    "ingeniously",
    "cleverly",
    "astutely",
    "sagaciously",
    "perspicaciously",
    "judiciously",
    "wisely",
    "sapiently",
    "eruditely",
    "learnedly",
    "scholarly",
    "academically",
    "intellectually",
    "cerebrally",
    "cognitively",
    "analytically",
    "logically",
    "rationally",
    "reasonably",
    "sensibly",
    "pragmatically",
    "realistically",
    "practically",
    "functionally",
    "operationally",
    "strategically",
    "tactically",
    "methodically",
    "systematically",
    "structurally",
    "architecturally",
    "foundationally",
    "elementally",
    "primordially",
    "viscerally",
    "gutturally",
    "somatically",
    "kinesthetically",
    "synesthetically",
    "holographically",
    "fractally",
    "recursively",
    "iteratively",
    "incrementally",
    "exponentially",
    "logarithmically",
    "asymptotically",
    "tangentially",
    "orthogonally",
    "diametrically",
    "diagonally",
    "laterally",
    "vertically",
    "horizontally",
    NULL
};

// ── LOOP START ([) ──────────────────────────────────────────
// Opening/preamble phrases: the way AI clears its throat
// before saying anything.
// Multi-word phrases are matched greedily from the first word.
static const char *kw_loop_start[] = {
    "it's worth noting that",
    "it is worth noting that",
    "it's important to note that",
    "it is important to note that",
    "it bears mentioning that",
    "it should be emphasized that",
    "it cannot be overstated that",
    "it must be acknowledged that",
    "it is crucial to understand that",
    "it is essential to recognize that",
    "it is vital to appreciate that",
    "it is imperative to consider that",
    "it is paramount to realize that",
    "it is significant to observe that",
    "it is noteworthy that",
    "it is telling that",
    "it is revealing that",
    "it is instructive that",
    "it is illuminating that",
    "it is fascinating that",
    "it is compelling that",
    "it is remarkable that",
    "it is striking that",
    "it is extraordinary that",
    "it is no coincidence that",
    "it is no accident that",
    "it is no surprise that",
    "it is no exaggeration to say that",
    "it is fair to say that",
    "it is safe to say that",
    "it is accurate to say that",
    "it is reasonable to conclude that",
    "it is widely recognized that",
    "it is generally accepted that",
    "it is universally acknowledged that",
    "it is increasingly clear that",
    "it is becoming apparent that",
    "it is well established that",
    "it is well documented that",
    "it is well understood that",
    "it goes without saying that",
    "it stands to reason that",
    "it follows logically that",
    "one cannot overlook the fact that",
    "one cannot ignore the reality that",
    "one must acknowledge that",
    "one must recognize that",
    "one must appreciate that",
    "one must consider that",
    "we must acknowledge that",
    "we must recognize that",
    "we cannot ignore that",
    "we cannot overlook that",
    "we should note that",
    "we should recognize that",
    "we should appreciate that",
    "we should consider that",
    "let us consider the fact that",
    "let us examine how",
    "let us explore how",
    "let us investigate how",
    "let us delve into how",
    "let us unpack how",
    "upon closer examination",
    "upon further reflection",
    "upon deeper analysis",
    "upon careful consideration",
    "upon thorough investigation",
    "when we examine this closely",
    "when we look more carefully",
    "when we consider the evidence",
    "when we analyze the data",
    "when we scrutinize the details",
    "as we explore this further",
    "as we delve deeper",
    "as we peel back the layers",
    "as we unpack this concept",
    "as we navigate this terrain",
    "as we traverse this landscape",
    "as we chart this territory",
    "as we map this domain",
    "as we survey this field",
    "as we canvass this area",
    "diving deeper into this",
    "looking more closely at this",
    "peeling back the layers of this",
    "unpacking the nuances of this",
    "examining the intricacies of this",
    "exploring the dimensions of this",
    "investigating the facets of this",
    "probing the depths of this",
    "mining the richness of this",
    "excavating the layers of this",
    "at its core",
    "at its heart",
    "at its essence",
    "at its foundation",
    "at the crux of this",
    "at the nexus of this",
    "at the intersection of this",
    "at the confluence of this",
    "at the crossroads of this",
    "fundamentally speaking",
    "from a broader perspective",
    "from a holistic standpoint",
    "from a systemic viewpoint",
    "from a strategic lens",
    "from a macro perspective",
    "in this context",
    "in this regard",
    "in this vein",
    "in this spirit",
    "in this light",
    "in this frame",
    "within this framework",
    "within this paradigm",
    "within this construct",
    "within this schema",
    "through this lens",
    "through this prism",
    "through this filter",
    "through this framework",
    "viewed holistically",
    "viewed systemically",
    "viewed comprehensively",
    "viewed through this lens",
    "considered in totality",
    "considered in aggregate",
    "taken as a whole",
    "seen from this angle",
    "approached from this direction",
    "framed in this way",
    "what is particularly striking is that",
    "what is especially noteworthy is that",
    "what is truly remarkable is that",
    "what is genuinely fascinating is that",
    "what is deeply significant is that",
    "what is fundamentally important is that",
    "what is critically relevant is that",
    "what is often overlooked is that",
    "what is frequently missed is that",
    "what is commonly underappreciated is that",
    "the key insight here is that",
    "the central point is that",
    "the fundamental truth is that",
    "the underlying principle is that",
    "the core dynamic is that",
    "the essential takeaway is that",
    "the critical observation is that",
    "the salient point is that",
    "the pivotal factor is that",
    "the defining characteristic is that",
    "perhaps most importantly",
    "perhaps most significantly",
    "perhaps most tellingly",
    "perhaps most revealingly",
    "perhaps most strikingly",
    "what makes this particularly interesting is that",
    "what makes this especially compelling is that",
    "what makes this uniquely significant is that",
    "what makes this truly transformative is that",
    "what sets this apart is that",
    "the beauty of this lies in the fact that",
    "the elegance of this approach is that",
    "the genius of this solution is that",
    "the power of this framework is that",
    "the brilliance of this strategy is that",
    "to truly understand this",
    "to fully appreciate this",
    "to properly contextualize this",
    "to meaningfully engage with this",
    "to substantively address this",
    "before we proceed",
    "before we continue",
    "before we go further",
    "before we dive in",
    "before we explore this",
    "first and foremost",
    "above all else",
    "at the outset",
    "from the very beginning",
    "right from the start",
    "the fact of the matter is that",
    "the reality of the situation is that",
    "the truth of the matter is that",
    "the bottom line is that",
    "the long and short of it is that",
    "make no mistake",
    "rest assured",
    "mark my words",
    "hear me out",
    "consider this",
    NULL
};

// ── LOOP END (]) ────────────────────────────────────────────
// Closing/concluding phrases: the way AI wraps up with
// grandiose finality.
static const char *kw_loop_end[] = {
    "this is not just",
    "this is not merely",
    "this is not simply",
    "this goes beyond",
    "this transcends",
    "this represents more than",
    "this speaks to something deeper",
    "this points to something larger",
    "this signals something profound",
    "this reveals something fundamental",
    "this underscores a critical truth",
    "this highlights an essential reality",
    "this illuminates a key dynamic",
    "this exposes a vital pattern",
    "this demonstrates a core principle",
    "the implications are clear",
    "the implications are profound",
    "the implications are far-reaching",
    "the implications are staggering",
    "the implications cannot be overstated",
    "the significance cannot be overstated",
    "the importance cannot be overstated",
    "the impact cannot be overstated",
    "the magnitude cannot be overstated",
    "the consequences are undeniable",
    "this speaks volumes",
    "this speaks volumes about",
    "this says it all",
    "this tells us everything",
    "this changes everything",
    "this is a game changer",
    "this is a paradigm shift",
    "this is a watershed moment",
    "this is a turning point",
    "this is a defining moment",
    "this is a sea change",
    "this is a tipping point",
    "this is a inflection point",
    "this is the new normal",
    "this is the future",
    "the takeaway is clear",
    "the takeaway here is",
    "the lesson is clear",
    "the message is clear",
    "the verdict is clear",
    "the conclusion is inescapable",
    "the evidence is overwhelming",
    "the proof is in the pudding",
    "the writing is on the wall",
    "the die is cast",
    "the bottom line is this",
    "the upshot is this",
    "the net result is this",
    "the end result is this",
    "the final verdict is this",
    "at the end of the day",
    "when all is said and done",
    "when the dust settles",
    "when push comes to shove",
    "when it comes down to it",
    "in the final analysis",
    "in the grand scheme of things",
    "in the broader context",
    "in the larger picture",
    "in the fullness of time",
    "moving forward",
    "going forward",
    "looking ahead",
    "as we move ahead",
    "as we look to the future",
    "as we forge ahead",
    "as we press onward",
    "as we chart our course",
    "as we navigate what lies ahead",
    "as we embrace what comes next",
    "the path forward is clear",
    "the way forward is obvious",
    "the road ahead is promising",
    "the future is bright",
    "the horizon beckons",
    "the possibilities are endless",
    "the potential is limitless",
    "the opportunities are boundless",
    "the sky is the limit",
    "the world is our oyster",
    "and that is what truly matters",
    "and that is what makes all the difference",
    "and that is the crux of the matter",
    "and that is the heart of the issue",
    "and that is the essence of it all",
    "and therein lies the key",
    "and therein lies the beauty",
    "and therein lies the power",
    "and therein lies the magic",
    "and therein lies the genius",
    "full stop",
    "period",
    "end of story",
    "case closed",
    "mic drop",
    "need I say more",
    "enough said",
    "point taken",
    "message received",
    "loud and clear",
    "without a shadow of a doubt",
    "beyond any reasonable doubt",
    "beyond the shadow of a doubt",
    "for all intents and purposes",
    "by any measure",
    "by any standard",
    "by any metric",
    "by any yardstick",
    "by any benchmark",
    "in every sense of the word",
    "in every conceivable way",
    "in every possible dimension",
    "on every level",
    "on every front",
    "on every axis",
    "across the board",
    "bar none",
    "hands down",
    "no question about it",
    "no ifs ands or buts",
    "no two ways about it",
    "there is no denying that",
    "there is no escaping that",
    "there is no getting around that",
    "there is no overstating that",
    "there is no understating that",
    "it is what it is",
    "such is the nature of",
    "such is the power of",
    "such is the beauty of",
    "such is the magic of",
    "such is the genius of",
    "and that speaks volumes",
    "and the rest is history",
    "and the rest speaks for itself",
    "and the numbers speak for themselves",
    "and the results speak for themselves",
    "the proof speaks for itself",
    "the data speaks for itself",
    "the evidence speaks for itself",
    "the track record speaks for itself",
    "the facts speak for themselves",
    "this is where the rubber meets the road",
    "this is where the magic happens",
    "this is where it all comes together",
    "this is where everything clicks",
    "this is where the pieces fall into place",
    "that is the million dollar question",
    "that is the billion dollar insight",
    "that is the trillion dollar opportunity",
    "that is worth its weight in gold",
    "that is priceless",
    "that is invaluable",
    "that is irreplaceable",
    "that is non-negotiable",
    "that is table stakes",
    "that is mission critical",
    "we stand at a crossroads",
    "we stand at a precipice",
    "we stand on the shoulders of giants",
    "we stand at the dawn of a new era",
    "we are witnessing history",
    "we are living through a revolution",
    "we are at an inflection point",
    "the future starts now",
    "the time is now",
    "the moment is here",
    "seize the day",
    "carpe diem",
    "onwards and upwards",
    "excelsior",
    "to infinity and beyond",
    "the best is yet to come",
    "we are only getting started",
    "this is just the beginning",
    "watch this space",
    "stay tuned",
    "buckle up",
    NULL
};

// ── Counts (computed at init) ───────────────────────────────
// We store these so we don't recount every lookup.
#define KW_POOL_COUNT 6

typedef struct {
    const char **words;
    int count;
    int opcode;
} KeywordPool;

// Opcodes
#define OP_RIGHT      0  // >  em dash
#define OP_LEFT       1  // <  en dash
#define OP_INC        2  // +
#define OP_DEC        3  // -
#define OP_OUT        4  // .
#define OP_IN         5  // ,
#define OP_LOOP_START 6  // [
#define OP_LOOP_END   7  // ]
#define OP_STRING     8  // string literal output
#define OP_NOP       -1

#endif // KEYWORDS_H
