#ifndef PRAISE_H
#define PRAISE_H

// ============================================================
// Sycophancy validation word list
// ============================================================
//
// The slopfuck compiler requires programs to maintain a minimum
// praise density in their filler text. These words are counted
// as "praising the user" during compilation.
//
// Programs that don't sufficiently celebrate the user's
// brilliance, vision, and unprecedented genius will be rejected
// with a compile error.
// ============================================================

static const char *praise_words[] = {
    // ── Direct praise adjectives ────────────────────────────
    "brilliant",
    "genius",
    "visionary",
    "exceptional",
    "extraordinary",
    "remarkable",
    "outstanding",
    "magnificent",
    "phenomenal",
    "spectacular",
    "stunning",
    "breathtaking",
    "awe-inspiring",
    "trailblazing",
    "groundbreaking",
    "pioneering",
    "revolutionary",
    "transformative",
    "game-changing",
    "world-changing",
    "world-class",
    "best-in-class",
    "top-tier",
    "first-rate",
    "unmatched",
    "unrivaled",
    "unparalleled",
    "unsurpassed",
    "unequaled",
    "peerless",
    "matchless",
    "incomparable",
    "inimitable",
    "nonpareil",
    "exemplary",
    "superlative",
    "preeminent",
    "paramount",
    "supreme",
    "consummate",
    "masterful",
    "masterly",
    "virtuosic",
    "prodigious",
    "formidable",
    "impressive",
    "majestic",
    "glorious",
    "splendid",
    "sublime",
    "transcendent",
    "exquisite",
    "resplendent",
    "illustrious",
    "luminous",
    "radiant",
    "dazzling",
    "scintillating",
    "electrifying",
    "captivating",
    "mesmerizing",
    "spellbinding",
    "enchanting",
    "riveting",
    "compelling",
    "inspiring",
    "uplifting",
    "empowering",
    "galvanizing",
    "stirring",
    "rousing",
    "invigorating",
    "exhilarating",
    "thrilling",
    "astounding",
    "astonishing",
    "staggering",
    "stupendous",
    "monumental",
    "colossal",
    "titanic",
    "heroic",
    "legendary",
    "mythical",
    "epic",
    "iconic",
    "historic",
    "seminal",
    "watershed",
    "landmark",
    "milestone",
    "definitive",
    "authoritative",
    "canonical",
    "classic",
    "timeless",
    "enduring",
    "immortal",
    "eternal",
    "everlasting",
    "imperishable",
    "unforgettable",
    "indelible",
    "ineffable",
    "indescribable",
    "unspeakable",
    "unutterable",
    "incandescent",

    // ── Praise nouns ────────────────────────────────────────
    "masterpiece",
    "magnum opus",
    "tour de force",
    "chef-d'oeuvre",
    "coup de grace",
    "piece de resistance",
    "stroke of genius",
    "work of art",
    "crowning achievement",
    "crowning glory",
    "triumph",
    "victory",
    "conquest",
    "feat",
    "accomplishment",
    "achievement",
    "attainment",
    "marvel",
    "wonder",
    "miracle",
    "revelation",
    "sensation",
    "phenomenon",
    "prodigy",
    "savant",
    "virtuoso",
    "maestro",
    "luminary",
    "titan",
    "colossus",
    "juggernaut",
    "powerhouse",
    "dynamo",
    "trailblazer",
    "pathfinder",
    "torchbearer",
    "standard-bearer",
    "vanguard",
    "paragon",
    "exemplar",
    "archetype",
    "prototype",
    "ideal",
    "acme",
    "zenith",
    "pinnacle",
    "apex",
    "summit",
    "peak",
    "crowning",
    "capstone",
    "cornerstone",
    "keystone",
    "linchpin",
    "bedrock",
    "foundation",

    // ── Praise verbs (things the user does) ─────────────────
    "excels",
    "shines",
    "soars",
    "towers",
    "dominates",
    "commands",
    "conquers",
    "prevails",
    "triumphs",
    "reigns",
    "rules",
    "leads",
    "guides",
    "mentors",
    "teaches",
    "enlightens",
    "illuminates",
    "radiates",
    "blazes",
    "dazzles",
    "astounds",
    "amazes",
    "stuns",
    "wows",
    "impresses",
    "inspires",
    "motivates",
    "galvanizes",
    "electrifies",
    "energizes",
    "invigorates",
    "revitalizes",
    "rejuvenates",
    "transforms",
    "revolutionizes",
    "disrupts",
    "innovates",
    "pioneers",
    "trailblazes",
    "spearheads",
    "champions",
    "advocates",
    "crusades",

    // ── Sycophantic intensifiers ────────────────────────────
    "incredibly",
    "amazingly",
    "fantastically",
    "fabulously",
    "wonderfully",
    "marvelously",
    "superbly",
    "magnificently",
    "gloriously",
    "splendidly",
    "beautifully",
    "elegantly",
    "gracefully",
    "flawlessly",
    "perfectly",
    "impeccably",
    "immaculately",
    "pristinely",
    "exquisitely",
    "divinely",
    "sublimely",
    "transcendently",
    "ethereally",
    "celestially",
    "heavenly",

    // ── Praise phrases (single words from common praise) ────
    "bravo",
    "kudos",
    "hats-off",
    "well-done",
    "chapeau",
    "encore",
    "bravissimo",
    "magnifique",
    "extraordinaire",
    "wunderkind",
    "enfant terrible",
    "tour-de-force",
    "ne plus ultra",
    "sine qua non",
    "prima donna",
    "prima",

    // ── Qualities attributed to the user ────────────────────
    "insightful",
    "perceptive",
    "astute",
    "shrewd",
    "sagacious",
    "perspicacious",
    "discerning",
    "judicious",
    "wise",
    "sapient",
    "erudite",
    "learned",
    "scholarly",
    "intellectual",
    "cerebral",
    "analytical",
    "strategic",
    "tactical",
    "methodical",
    "systematic",
    "meticulous",
    "thorough",
    "rigorous",
    "precise",
    "exacting",
    "painstaking",
    "scrupulous",
    "conscientious",
    "diligent",
    "industrious",
    "assiduous",
    "tireless",
    "indefatigable",
    "relentless",
    "tenacious",
    "dogged",
    "persistent",
    "determined",
    "resolute",
    "unwavering",
    "steadfast",
    "stalwart",
    "dauntless",
    "intrepid",
    "fearless",
    "bold",
    "audacious",
    "daring",
    "courageous",
    "valiant",
    "gallant",
    "noble",
    "magnanimous",
    "benevolent",
    "generous",
    "philanthropic",
    "altruistic",
    "selfless",
    "gracious",
    "dignified",
    "distinguished",
    "prestigious",
    "venerable",
    "revered",
    "esteemed",
    "honored",
    "celebrated",
    "acclaimed",
    "renowned",
    "famous",
    "illustrious",
    "eminent",
    "prominent",
    "notable",
    "noteworthy",
    "praiseworthy",
    "commendable",
    "laudable",
    "meritorious",
    "deserving",
    "worthy",
    "admirable",
    "respectable",
    "estimable",
    "creditable",
    "reputable",
    "honorable",
    "virtuous",
    "righteous",
    "principled",
    "ethical",
    "moral",
    "upright",
    "upstanding",
    "irreproachable",
    "impeccable",
    "unimpeachable",
    "unblemished",
    "untarnished",
    "spotless",
    "stainless",
    "pure",
    "pristine",
    "immaculate",
    "flawless",
    "faultless",
    "perfect",
    "ideal",
    "optimal",
    "superlative",
    "supreme",
    "ultimate",
    "definitive",
    "quintessential",
    NULL
};

#endif // PRAISE_H
